language: java
jdk:
  - oraclejdk8

sudo: false
addons:
  apt:
    packages:
      - oracle-java9-installer

env:
  matrix:
    - TERM=dumb
  global:
    - secure: Irtg0m2UESxQ6ay6gDryh4JM1c5Z9OT882V3iaLAbRmecfOlcVFPlgjmQGnqBWlCNesj5bp30zQJhBuS38k6cDRXd7Y0HPFCqt8IFrKrIhV6JNCQSDST7dU2kHtX+CnhgShyFLHV3CrOdaY/5rcvMU7XGN3ytX024+147x0BvFw=
    - secure: NGNsvBLaE0R40chmarx1ryDqoHv1wiycw96EvOUrFafQpjUDeEw5q0W2572IIzY5NmyUw57WQx0tETyniJaJB7d5t//skUNAa1wIDms7RwqsQUllZaPlZPJak7JXV6UnSfGqISXaaGd6OxxQFMioFl/bhOyivtL3n98Osyqm6pQ=
    - secure: DkJhDrFVkgQi33cRBuBS5LHpzEEMqAPVm4HiE6jQ2Ts1nFZHvkVsrrPIOgqNEXtiAak1zEy34tBB3nddq7YyJALHO/bbT7E9pIBi3A7A18UchQzl/60lhJ/NKD9+wh2UKHgZFvHyiLPXLBFI9WHp+xPEm4kIVlqmiRqYXFKbtJk=

install:
  - ./gradlew --version

before_script:
  - envsubst < .travis/maven-settings.xml > ~/.m2/settings.xml

script:
  - ./gradlew build jacocoTestReport --stacktrace --continue

after_success:
  - 'if [ -n "$GITHUB_TOKEN" ]; then ./gradlew publishGhPages --stacktrace -PgithubUser="${GITHUB_TOKEN}" -PgithubPassword=""; fi'
  - 'if [ -n "$JFROG_USER" ]; then ./gradlew release --stacktrace; fi'
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - ./cnf/cache
